baseURL = "https://ioslide.github.io/"
copyright = "© XHY"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Gallery"

[params]
  defaultTheme = "dark"
  description = "Timeline"
  title = "XHY Gallery"
  [params.author]
    email = "im@xhy.im"
    name = "Timeline"
  [params.socialIcons]
    email = "mailto:im@xhy.im"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.146.7"
  [[module.imports]]
    path = "github.com/ioslide/hugo"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3

[services]
  [services.rss]
    limit = 100